[tool.poetry]
name = "pynes"
version = "3.0.0"
description = "pyNES"
authors = ["Guto Maia <guto@guto.net>"]

[tool.poetry.dependencies]
python = "^3.12"
nesasm = "^0.0.9"
meta = "^1.0.2"

[tool.poetry.group.dev.dependencies]
bandit = "^1.9"
black = "^25.1"
flake8 = "^7.3"
pytest = "^8.4"
pytest-cov = "^6.2"
pytest-watch = "^4.2.0"
py65 = "^1.1.0"
poetry-bumpversion = "^0.3.3"

[tool.black]
line-length = 79
skip-string-normalization = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry_bumpversion.file."pynes/__init__.py"]

[tool.poetry.scripts]
pynes = "pynes.command:main"