import ast

from pynes.translator import PythonTo6502, VarTable

ENTRY_POINTS = ('reset', 'nmi', 'irq')

RESET_PREAMBLE = [
    'SEI',
    'CLD',
    'LDX #$FF',
    'TXS',
]


class CartVarTable(VarTable):
    """Variable collector that ignores called function names."""

    def visit_Call(self, node):
        for arg in node.args:
            self.visit(arg)


class Cart:
    """NES cartridge builder: turns a Python module with entry point
    decorators (@reset, @nmi, @irq) into a complete nesasm source,
    linking the runtime of the given libraries."""

    def __init__(
        self,
        libraries=None,
        prg_banks=1,
        chr_banks=0,
        mapper=0,
        mirroring=1,
        org=0xC000,
    ):
        self.libraries = libraries or []
        self.prg_banks = prg_banks
        self.chr_banks = chr_banks
        self.mapper = mapper
        self.mirroring = mirroring
        self.org = org

    def _entry_name(self, node):
        for decorator in node.decorator_list:
            if isinstance(decorator, ast.Name) and decorator.id in (
                ENTRY_POINTS
            ):
                return decorator.id
        return None

    def _collect_entries(self, tree):
        entries = {}
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                entry = self._entry_name(node)
                if entry is None:
                    raise NotImplementedError(
                        'User-defined functions are not supported yet: '
                        f'{node.name!r}'
                    )
                entries[entry] = node
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                continue
            else:
                raise NotImplementedError(
                    'Unsupported top-level statement: '
                    f'{type(node).__name__}'
                )
        if 'reset' not in entries:
            raise ValueError('Missing @reset entry point')
        return entries

    def _translate_body(self, node):
        translator = PythonTo6502(libraries=self.libraries)
        for stmt in node.body:
            translator.visit(stmt)
        return translator.output

    def _collect_vars(self, entries):
        vartable = CartVarTable()
        for node in entries.values():
            for stmt in node.body:
                vartable.visit(stmt)
        address = 0x00
        for var in vartable.vars.values():
            var.address = address
            address += 1
        return vartable.vars

    def compile(self, source):
        tree = ast.parse(source)
        entries = self._collect_entries(tree)
        variables = self._collect_vars(entries)

        out = []
        out.append('; Generated by pyNES')
        out.append(f'.inesprg {self.prg_banks}')
        out.append(f'.ineschr {self.chr_banks}')
        out.append(f'.inesmap {self.mapper}')
        out.append(f'.inesmir {self.mirroring}')
        out.append('')

        if variables:
            out.append('.rsset $0000')
            for var in variables.values():
                out.append(f'{var.label} .rs 1')
            out.append('')

        out.append('.bank 0')
        out.append(f'.org ${self.org:04X}')
        out.append('')

        out.append('RESET:')
        out.extend(RESET_PREAMBLE)
        out.extend(self._translate_body(entries['reset']))
        out.append('forever:')
        out.append('JMP forever')
        out.append('')

        out.append('NMI:')
        if 'nmi' in entries:
            out.extend(self._translate_body(entries['nmi']))
        out.append('RTI')
        out.append('')

        out.append('IRQ:')
        if 'irq' in entries:
            out.extend(self._translate_body(entries['irq']))
        out.append('RTI')
        out.append('')

        for library in self.libraries:
            out.append(f'; runtime: {library.name}')
            out.extend(library.runtime_asm)
            out.append('')

        out.append(f'.bank {self.prg_banks * 2 - 1}')
        out.append('.org $FFFA')
        out.append('.dw NMI')
        out.append('.dw RESET')
        out.append('.dw IRQ')

        return '\n'.join(out)
